# Site settings
title: Some words
name: brucevoin # your name
email: brucevoin@gmail.com # your email address
description: >
    this is some words i want to say. # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username:  # 
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
